#include "DBUS_LED.h"

void LED_GPIOG_Init(void)
{
	GPIO_InitTypeDef GPIO_LED_Init;
	__HAL_RCC_GPIOG_CLK_ENABLE();
	
	GPIO_LED_Init.Pin=GPIO_PIN_1;
	GPIO_LED_Init.Mode=GPIO_MODE_OUTPUT_PP;
	GPIO_LED_Init.Speed=GPIO_SPEED_FREQ_LOW;
	GPIO_LED_Init.Pull=GPIO_NOPULL;
	HAL_GPIO_Init(GPIOG,&GPIO_LED_Init);
	HAL_GPIO_WritePin(GPIOG,GPIO_PIN_1,GPIO_PIN_SET);
	
	GPIO_LED_Init.Pin=GPIO_PIN_2;
	HAL_GPIO_Init(GPIOG,&GPIO_LED_Init);
	HAL_GPIO_WritePin(GPIOG,GPIO_PIN_2,GPIO_PIN_SET);
	
	GPIO_LED_Init.Pin=GPIO_PIN_3;
	HAL_GPIO_Init(GPIOG,&GPIO_LED_Init);
	HAL_GPIO_WritePin(GPIOG,GPIO_PIN_3,GPIO_PIN_SET);
	
	GPIO_LED_Init.Pin=GPIO_PIN_4;
	HAL_GPIO_Init(GPIOG,&GPIO_LED_Init);
	HAL_GPIO_WritePin(GPIOG,GPIO_PIN_4,GPIO_PIN_SET);
	
	GPIO_LED_Init.Pin=GPIO_PIN_5;
	HAL_GPIO_Init(GPIOG,&GPIO_LED_Init);
	HAL_GPIO_WritePin(GPIOG,GPIO_PIN_5,GPIO_PIN_SET);
	
	GPIO_LED_Init.Pin=GPIO_PIN_6;
	HAL_GPIO_Init(GPIOG,&GPIO_LED_Init);
	HAL_GPIO_WritePin(GPIOG,GPIO_PIN_6,GPIO_PIN_SET);
	
	GPIO_LED_Init.Pin=GPIO_PIN_7;
	HAL_GPIO_Init(GPIOG,&GPIO_LED_Init);
	HAL_GPIO_WritePin(GPIOG,GPIO_PIN_7,GPIO_PIN_SET);
	
	GPIO_LED_Init.Pin=GPIO_PIN_8;
	HAL_GPIO_Init(GPIOG,&GPIO_LED_Init);
	HAL_GPIO_WritePin(GPIOG,GPIO_PIN_8,GPIO_PIN_SET);
}
